author = "Daniel Jay Hartman"
baseURL = "/"
builddrafts = false
canonifyurls = true
contentdir = "content"
# googleAnalytics = "UA-123-45"
languageCode = "en-us"
layoutdir = "layouts"
pluralizelisttitles = false
publishdir = "public"
pygmentsuseclasses = true
theme = "cocoa"
title = "Daniel Jay Hartman"
[[menu.main]]
identifier = "contact"
name = "Contact <span class='ion-ios-email-outline'></span>"
url = "/contact/"
weight = -100
[[menu.main]]
identifier = "blog"
name = "Blog <span class='ion-ios-paper-outline'></span>"
url = "/blog/"
weight = -110
[[menu.main]]
identifier = "about"
name = "About <span class='ion-ios-person-outline'></span>"
url = "/about/"
weight = -120
[[menu.main]]
identifier = "github"
name = "Github <span class='ion-social-github-outline'></span>"
url = "https://www.github.com/dj"
weight = -100
[[menu.main]]
identifier = "twitter"
name = "Twitter <span class='ion-social-twitter-outline'></span>"
url = "https://www.twitter.com/deej_codes"
weight = -80
[[menu.main]]
identifier = "linkedin"
name = "LinkedIn <span class='ion-social-linkedin-outline'></span>"
url = "https://www.linkedin.com/in/daniel-hartman-5966a35a/"
weight = -90
[params]
author = "Daniel Hartman"
# avatar = "/uploads/2017/08/23/circle-avatar.png"
gravatar = "8676179396609ff0a32cbda439a3a0d9"
cachebuster = true
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Software development blog."
# email = "you@example.space"
extracssfiles = ["/css/override.css"]
# faviconfile = "img/leaf.ico"
gatracker = "XYZ"
github = "https://github.com/dj"
highlightjs = true
i18n_flags = false
initials = "DJH"
# instagram = "//instagram.com/you"
lang = "en"
latestpostscount = 5
linkedin = "https://www.linkedin.com/in/daniel-hartman-5966a35a"
noshowreadtime = false
piwik = false
selfintro = "Software Engineer"
[permalinks]
blog = "/:slug/"
