author = "Daniel Jay Hartman"
baseURL = "/"
builddrafts = false
canonifyurls = true
contentdir = "content"
# googleAnalytics = "UA-123-45"
languageCode = "en-us"
layoutdir = "layouts"
pluralizelisttitles = false
publishdir = "public"
pygmentsuseclasses = true
theme = "cocoa"
title = "Daniel Jay Hartman"
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = -100
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = -110
[params]
author = "Daniel Jay Hartman"
# avatar = "/uploads/2017/08/23/circle-avatar.png"
gravatar = "8676179396609ff0a32cbda439a3a0d9"
cachebuster = true
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Don't panic"
# email = "you@example.space"
extracssfiles = ["/css/override.css"]
# faviconfile = "img/leaf.ico"
gatracker = "XYZ"
github = "//github.com/dj"
highlightjs = true
i18n_flags = false
initials = "DJH"
# instagram = "//instagram.com/you"
lang = "en"
latestpostscount = 5
linkedin = "https://www.linkedin.com/in/daniel-hartman-5966a35a"
noshowreadtime = false
piwik = false
selfintro = "Just a boy and his blog. Software engineer."
[permalinks]
blog = "/:slug/"
